#include "LogMacros.h"

DEFINE_LOG_CATEGORY(LogPlayerCharacter)
DEFINE_LOG_CATEGORY(LogUserWidget)
DEFINE_LOG_CATEGORY(LogEquipment)
DEFINE_LOG_CATEGORY(LogInteractable)
DEFINE_LOG_CATEGORY(LogQuest)
DEFINE_LOG_CATEGORY(LogItemData)